spring:
  application:
    name: miniautorizador

  security:
    user:
      name: username       # usuário para autenticação Basic
      password: password  # senha para autenticação Basic
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    password:
    driver-classe-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect